# Generated by Django 5.2.17 on 2026-09-04 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_invoice_invoice_number"),
        ("schools", "0005_alter_campus_code_alter_department_code_and_more"),
        ("students", "0011_achievement_platform_mode_rls"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "status", "due_date"],
                name="idx_invoice_org_status_due",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "status", "paid_at"],
                name="idx_payment_org_status_paid",
            ),
        ),
    ]
