# Generated by Django 5.2.17 on 2026-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
