# Generated by Django 5.2.17 on 2026-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_append_only_stock_movement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_number",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
