from django.urls import path

from .views import (
    AssessmentDetailView,
    AssessmentListCreateView,
    ExamDetailView,
    ExamListCreateView,
    ExamScheduleDetailView,
    ExamScheduleListCreateView,
    GradeBandDetailView,
    GradeBandListCreateView,
    GradingSchemeDetailView,
    GradingSchemeListCreateView,
    InvigilatorDeleteView,
    InvigilatorListCreateView,
    ReportCardDetailView,
    ReportCardListCreateView,
    ResultDetailView,
    ResultListCreateView,
    ResultPublishView,
    ResultReviewView,
    ResultSubmitView,
    ResultVerifyView,
    ResultWorkflowStateListView,
)

urlpatterns = [
    path("grading-schemes", GradingSchemeListCreateView.as_view(), name="grading-scheme-list-create"),
    path(
        "grading-schemes/<uuid:public_id>",
        GradingSchemeDetailView.as_view(),
        name="grading-scheme-detail",
    ),
    path("grade-bands", GradeBandListCreateView.as_view(), name="grade-band-list-create"),
    path("grade-bands/<uuid:public_id>", GradeBandDetailView.as_view(), name="grade-band-detail"),
    path("exams", ExamListCreateView.as_view(), name="exam-list-create"),
    path("exams/<uuid:public_id>", ExamDetailView.as_view(), name="exam-detail"),
    path("exam-schedules", ExamScheduleListCreateView.as_view(), name="exam-schedule-list-create"),
    path(
        "exam-schedules/<uuid:public_id>",
        ExamScheduleDetailView.as_view(),
        name="exam-schedule-detail",
    ),
    path("invigilators", InvigilatorListCreateView.as_view(), name="invigilator-list-create"),
    path("invigilators/<uuid:public_id>", InvigilatorDeleteView.as_view(), name="invigilator-delete"),
    path("assessments", AssessmentListCreateView.as_view(), name="assessment-list-create"),
    path("assessments/<uuid:public_id>", AssessmentDetailView.as_view(), name="assessment-detail"),
    path("results", ResultListCreateView.as_view(), name="result-list-create"),
    path("results/<uuid:public_id>", ResultDetailView.as_view(), name="result-detail"),
    path("results/<uuid:public_id>/submit", ResultSubmitView.as_view(), name="result-submit"),
    path("results/<uuid:public_id>/review", ResultReviewView.as_view(), name="result-review"),
    path("results/<uuid:public_id>/verify", ResultVerifyView.as_view(), name="result-verify"),
    path("results/<uuid:public_id>/publish", ResultPublishView.as_view(), name="result-publish"),
    path(
        "result-workflow-states",
        ResultWorkflowStateListView.as_view(),
        name="result-workflow-state-list",
    ),
    path("report-cards", ReportCardListCreateView.as_view(), name="report-card-list-create"),
    path("report-cards/<uuid:public_id>", ReportCardDetailView.as_view(), name="report-card-detail"),
]
