# Generated by Django 5.2.17 on 2026-09-03 10:29
#
# The bare PDF-job ReportCard is replaced by apps.report_cards' richer
# engine (see that app's models). score_category backfills to "exam" for
# existing assessment_type="exam" rows so historical data lands in the
# right report-card bucket without an admin having to re-tag everything
# by hand; every other existing assessment defaults to "ca" via the field
# default above, which is the right assumption for test/quiz/assignment/
# project/practical UNLESS an admin already ran some of those through the
# CBT question-bank flow — those need manually re-tagging to "cbt" once,
# after which score_category is independently editable per assessment.
from django.db import migrations, models


def backfill_exam_score_category(apps, schema_editor):
    Assessment = apps.get_model("examinations", "Assessment")
    Assessment.objects.filter(assessment_type="exam").update(score_category="exam")


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0009_platform_mode_rls_question_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="score_category",
            field=models.CharField(
                choices=[
                    ("ca", "Continuous Assessment"),
                    ("cbt", "CBT"),
                    ("exam", "Examination"),
                ],
                default="ca",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_exam_score_category, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="ReportCard",
        ),
    ]
