# Generated by Django 5.2.17 on 2026-09-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0010_remove_report_card_add_score_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image_storage_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
