# Generated by Django 5.0.14 on 2026-08-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_enable_rls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guardianstudent",
            options={"ordering": ["-created_at"]},
        ),
    ]
