# Generated by Django 5.2.17 on 2026-08-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_add_student_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
