# Generated by Django 5.2.17 on 2026-08-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_alter_student_admission_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo_storage_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
