# Generated by Django 5.2.17 on 2026-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0004_platform_mode_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("announcement", "Announcement"),
                    ("system", "System"),
                    ("fee_reminder", "Fee reminder"),
                ],
                max_length=20,
            ),
        ),
    ]
