# Generated by Django 5.2.17 on 2026-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_platform_mode_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
