# Generated by Django 5.2.17 on 2026-09-04 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_alter_subject_code"),
        ("attendance", "0005_append_only_audit"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["organization", "date"], name="idx_attendance_org_date"
            ),
        ),
    ]
