# Generated by Django 5.2.17 on 2026-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_platform_mode_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="school",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
