# Generated by Django 5.2.17 on 2026-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_add_staff_contact_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="employee_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
