# Generated by Django 5.2.17 on 2026-08-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0004_platform_mode_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostelbed",
            name="bed_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="hostelroom",
            name="room_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
