from django.urls import path

from .views import (
    AttemptAnswerView,
    AttemptDetailView,
    AttemptEventView,
    AttemptFlagView,
    AttemptHeartbeatView,
    AttemptStartView,
    AttemptSubmitView,
    CBTExamArchiveView,
    CBTExamDetailView,
    CBTExamListCreateView,
    CBTExamPublishView,
    CBTMediaDetailView,
    CBTMediaListView,
    CBTMediaUploadView,
    ExamAnalyticsView,
    ExamAttemptDetailView,
    ExamAttemptListView,
    ExamCandidateBulkFromClassArmView,
    ExamCandidateDetailView,
    ExamCandidateListCreateView,
    ExamGenerateQuestionsView,
    ExamQuestionDetailView,
    ExamQuestionListCreateView,
    ExamQuestionReorderView,
    ExamSectionDetailView,
    ExamSectionListCreateView,
    QuestionApproveView,
    QuestionBlockDetailView,
    QuestionBlockListCreateView,
    QuestionBulkImportView,
    QuestionDetailView,
    QuestionDuplicateView,
    QuestionListCreateView,
    QuestionOptionDetailView,
    QuestionOptionListCreateView,
    QuestionRejectView,
    QuestionSubmitView,
    QuestionVersionListView,
    StudentAnswerGradeView,
    TopicDetailView,
    TopicListCreateView,
)

urlpatterns = [
    path("cbt/topics", TopicListCreateView.as_view(), name="cbt-topic-list-create"),
    path("cbt/topics/<uuid:public_id>", TopicDetailView.as_view(), name="cbt-topic-detail"),
    path("cbt/questions", QuestionListCreateView.as_view(), name="cbt-question-list-create"),
    path("cbt/questions/bulk-import", QuestionBulkImportView.as_view(), name="cbt-question-bulk-import"),
    path("cbt/questions/<uuid:public_id>", QuestionDetailView.as_view(), name="cbt-question-detail"),
    path("cbt/questions/<uuid:public_id>/submit", QuestionSubmitView.as_view(), name="cbt-question-submit"),
    path("cbt/questions/<uuid:public_id>/approve", QuestionApproveView.as_view(), name="cbt-question-approve"),
    path("cbt/questions/<uuid:public_id>/reject", QuestionRejectView.as_view(), name="cbt-question-reject"),
    path(
        "cbt/questions/<uuid:public_id>/duplicate",
        QuestionDuplicateView.as_view(),
        name="cbt-question-duplicate",
    ),
    path(
        "cbt/questions/<uuid:public_id>/versions",
        QuestionVersionListView.as_view(),
        name="cbt-question-version-list",
    ),
    path(
        "cbt/questions/<uuid:public_id>/blocks",
        QuestionBlockListCreateView.as_view(),
        name="cbt-question-block-list-create",
    ),
    path(
        "cbt/questions/<uuid:public_id>/blocks/<uuid:block_public_id>",
        QuestionBlockDetailView.as_view(),
        name="cbt-question-block-detail",
    ),
    path(
        "cbt/questions/<uuid:public_id>/options",
        QuestionOptionListCreateView.as_view(),
        name="cbt-question-option-list-create",
    ),
    path(
        "cbt/questions/<uuid:public_id>/options/<uuid:option_public_id>",
        QuestionOptionDetailView.as_view(),
        name="cbt-question-option-detail",
    ),
    path("cbt/media", CBTMediaListView.as_view(), name="cbt-media-list"),
    path("cbt/media/upload", CBTMediaUploadView.as_view(), name="cbt-media-upload"),
    path("cbt/media/<uuid:public_id>", CBTMediaDetailView.as_view(), name="cbt-media-detail"),
    path("cbt/exams", CBTExamListCreateView.as_view(), name="cbt-exam-list-create"),
    path("cbt/exams/<uuid:public_id>", CBTExamDetailView.as_view(), name="cbt-exam-detail"),
    path("cbt/exams/<uuid:public_id>/publish", CBTExamPublishView.as_view(), name="cbt-exam-publish"),
    path("cbt/exams/<uuid:public_id>/archive", CBTExamArchiveView.as_view(), name="cbt-exam-archive"),
    path(
        "cbt/exams/<uuid:public_id>/generate-questions",
        ExamGenerateQuestionsView.as_view(),
        name="cbt-exam-generate-questions",
    ),
    path("cbt/exams/<uuid:public_id>/analytics", ExamAnalyticsView.as_view(), name="cbt-exam-analytics"),
    path(
        "cbt/exams/<uuid:public_id>/sections",
        ExamSectionListCreateView.as_view(),
        name="cbt-exam-section-list-create",
    ),
    path(
        "cbt/exams/<uuid:public_id>/sections/<uuid:section_public_id>",
        ExamSectionDetailView.as_view(),
        name="cbt-exam-section-detail",
    ),
    path(
        "cbt/exams/<uuid:public_id>/questions",
        ExamQuestionListCreateView.as_view(),
        name="cbt-exam-question-list-create",
    ),
    path(
        "cbt/exams/<uuid:public_id>/questions/<uuid:exam_question_public_id>",
        ExamQuestionDetailView.as_view(),
        name="cbt-exam-question-detail",
    ),
    path(
        "cbt/exams/<uuid:public_id>/questions/reorder",
        ExamQuestionReorderView.as_view(),
        name="cbt-exam-question-reorder",
    ),
    path(
        "cbt/exams/<uuid:public_id>/candidates",
        ExamCandidateListCreateView.as_view(),
        name="cbt-exam-candidate-list-create",
    ),
    path(
        "cbt/exams/<uuid:public_id>/candidates/<uuid:candidate_public_id>",
        ExamCandidateDetailView.as_view(),
        name="cbt-exam-candidate-detail",
    ),
    path(
        "cbt/exams/<uuid:public_id>/candidates/from-class-arm",
        ExamCandidateBulkFromClassArmView.as_view(),
        name="cbt-exam-candidate-from-class-arm",
    ),
    path(
        "cbt/exams/<uuid:public_id>/attempts",
        ExamAttemptListView.as_view(),
        name="cbt-exam-attempt-list",
    ),
    path(
        "cbt/exams/<uuid:public_id>/attempts/<uuid:attempt_public_id>",
        ExamAttemptDetailView.as_view(),
        name="cbt-exam-attempt-detail",
    ),
    path(
        "cbt/answers/<uuid:public_id>/grade",
        StudentAnswerGradeView.as_view(),
        name="cbt-answer-grade",
    ),
    path(
        "cbt/my/candidates/<uuid:candidate_public_id>/start-attempt",
        AttemptStartView.as_view(),
        name="cbt-my-attempt-start",
    ),
    path("cbt/my/attempts/<uuid:public_id>", AttemptDetailView.as_view(), name="cbt-my-attempt-detail"),
    path(
        "cbt/my/attempts/<uuid:public_id>/heartbeat",
        AttemptHeartbeatView.as_view(),
        name="cbt-my-attempt-heartbeat",
    ),
    path(
        "cbt/my/attempts/<uuid:public_id>/answers",
        AttemptAnswerView.as_view(),
        name="cbt-my-attempt-answer",
    ),
    path("cbt/my/attempts/<uuid:public_id>/flag", AttemptFlagView.as_view(), name="cbt-my-attempt-flag"),
    path(
        "cbt/my/attempts/<uuid:public_id>/events",
        AttemptEventView.as_view(),
        name="cbt-my-attempt-event",
    ),
    path(
        "cbt/my/attempts/<uuid:public_id>/submit",
        AttemptSubmitView.as_view(),
        name="cbt-my-attempt-submit",
    ),
]
