# Generated by Django 5.2.17 on 2026-09-03 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0005_alter_subject_code"),
        ("schools", "0005_alter_campus_code_alter_department_code_and_more"),
        ("students", "0011_achievement_platform_mode_rls"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("report_card_number", models.CharField(max_length=30, unique=True)),
                ("verification_code", models.CharField(max_length=64, unique=True)),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_possible_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("class_position", models.PositiveIntegerField(blank=True, null=True)),
                ("class_size", models.PositiveIntegerField(default=0)),
                ("attendance_present", models.PositiveIntegerField(default=0)),
                ("attendance_absent", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("teacher_comment", models.TextField(blank=True, default="")),
                ("principal_comment", models.TextField(blank=True, default="")),
                ("next_term_begins", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="schools.academicyear",
                    ),
                ),
                (
                    "class_arm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="academics.classarm",
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="academics.classlevel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="schools.term",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_cards_report_card",
                "ordering": ["-academic_year", "term", "student"],
            },
        ),
        migrations.CreateModel(
            name="ReportCardSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "ca_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "ca_max_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "cbt_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "cbt_max_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "exam_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "exam_max_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("grade", models.CharField(blank=True, default="", max_length=10)),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                ("class_position", models.PositiveIntegerField(blank=True, null=True)),
                ("teacher_comment", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "report_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="report_cards.reportcard",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="academics.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_cards_report_card_subject",
                "ordering": ["subject__name"],
            },
        ),
        migrations.CreateModel(
            name="ReportCardWeighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "ca_weight",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "cbt_weight",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "exam_weight",
                    models.DecimalField(decimal_places=2, default=40, max_digits=5),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_card_weightings",
                        to="schools.school",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_cards_weighting",
            },
        ),
        migrations.AddConstraint(
            model_name="reportcard",
            constraint=models.UniqueConstraint(
                fields=("student", "academic_year", "term"),
                name="uq_report_card_student_year_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportcardsubject",
            constraint=models.UniqueConstraint(
                fields=("report_card", "subject"),
                name="uq_report_card_subject_card_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportcardweighting",
            constraint=models.UniqueConstraint(
                fields=("school",), name="uq_report_card_weighting_school"
            ),
        ),
    ]
