# Generated by Django 5.2.17 on 2026-09-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_cards", "0004_platform_mode_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="pdf_error_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="pdf_file_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="pdf_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
