# Generated by Django 5.2.17 on 2026-09-06 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_alter_subject_code"),
        ("cbt", "0004_seed_permissions"),
        ("schools", "0005_alter_campus_code_alter_department_code_and_more"),
        ("students", "0011_achievement_platform_mode_rls"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CBTExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("ca", "Continuous Assessment"),
                            ("test", "Test"),
                            ("quiz", "Quiz"),
                            ("midterm", "Mid-Term"),
                            ("terminal", "Terminal"),
                            ("mock", "Mock"),
                            ("entrance", "Entrance"),
                            ("promotion", "Promotion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("pass_mark", models.DecimalField(decimal_places=2, max_digits=8)),
                ("instructions", models.JSONField(blank=True, default=dict)),
                ("randomize_questions", models.BooleanField(default=True)),
                ("randomize_options", models.BooleanField(default=True)),
                ("allow_resume", models.BooleanField(default=True)),
                ("negative_marking", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("marking", "Marking"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="schools.academicyear",
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="academics.classlevel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="schools.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="academics.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_exams",
                        to="schools.term",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cbt_exam",
                "ordering": ["-start_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("candidate_number", models.CharField(blank=True, max_length=50)),
                ("extra_time_minutes", models.PositiveIntegerField(default=0)),
                ("is_eligible", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="cbt.cbtexam",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cbt_candidacies",
                        to="students.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cbt_exam_candidate",
                "ordering": ["exam", "candidate_number"],
            },
        ),
        migrations.CreateModel(
            name="ExamSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("instructions", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveIntegerField()),
                (
                    "marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cbt.cbtexam",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cbt_exam_section",
                "ordering": ["exam", "order"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "marks_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="cbt.cbtexam",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_questions",
                        to="cbt.question",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_questions",
                        to="cbt.examsection",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_exam_question",
                "ordering": ["exam", "order"],
            },
        ),
        migrations.AddConstraint(
            model_name="cbtexam",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uq_cbt_exam_org_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="examcandidate",
            constraint=models.UniqueConstraint(
                fields=("exam", "student"), name="uq_cbt_exam_candidate_exam_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="examsection",
            constraint=models.UniqueConstraint(
                fields=("exam", "order"), name="uq_cbt_exam_section_exam_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="examquestion",
            constraint=models.UniqueConstraint(
                fields=("exam", "question"), name="uq_cbt_exam_question_exam_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="examquestion",
            constraint=models.UniqueConstraint(
                fields=("exam", "order"), name="uq_cbt_exam_question_exam_order"
            ),
        ),
    ]
