# Generated by Django 5.2.17 on 2026-09-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0012_seed_attempt_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="option_orders",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
