# Generated by Django 5.2.17 on 2026-09-06 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0013_examattempt_option_orders"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="flagged_for_review",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ExamAttemptEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tab_hidden", "Tab Hidden"),
                            ("tab_visible", "Tab Visible"),
                            ("fullscreen_exit", "Fullscreen Exit"),
                            ("fullscreen_enter", "Fullscreen Enter"),
                            ("window_blur", "Window Blur"),
                            ("window_focus", "Window Focus"),
                            ("copy_attempt", "Copy Attempted"),
                            ("paste_attempt", "Paste Attempted"),
                            ("right_click", "Right-Click Attempted"),
                            ("disconnect", "Connection Lost"),
                            ("reconnect", "Reconnected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cbt.examattempt",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cbt_exam_attempt_event",
                "ordering": ["attempt", "created_at"],
            },
        ),
    ]
