# Generated by Django 5.0.14 on 2026-08-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0004_enable_rls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guardianstudent",
            options={"ordering": ["-created_at"]},
        ),
    ]
